// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GRMTestApp.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GRMTestApp.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Name = "Item1",
                            Position = 1,
                            Score = 0,
                            Value = 0
                        },
                        new
                        {
                            ItemID = 2,
                            Name = "Item2",
                            Position = 2,
                            Score = 0,
                            Value = 0
                        },
                        new
                        {
                            ItemID = 3,
                            Name = "Item3",
                            Position = 3,
                            Score = 0,
                            Value = 0
                        },
                        new
                        {
                            ItemID = 4,
                            Name = "Item4",
                            Position = 4,
                            Score = 0,
                            Value = 0
                        },
                        new
                        {
                            ItemID = 5,
                            Name = "Item5",
                            Position = 5,
                            Score = 0,
                            Value = 0
                        },
                        new
                        {
                            ItemID = 6,
                            Name = "Item6",
                            Position = 6,
                            Score = 0,
                            Value = 0
                        });
                });

            modelBuilder.Entity("GRMTestApp.Models.Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Away")
                        .HasColumnType("int");

                    b.Property<int>("Home")
                        .HasColumnType("int");

                    b.Property<bool>("isPlayed")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Match");
                });
#pragma warning restore 612, 618
        }
    }
}
